name: ci

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2.0.5
        with:
          version: 0.14.1

      - run: zig build
